name: Cypress Tests with Mochawesome (Multi-Browser)

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox, electron, edge]

    name: Run on ${{ matrix.browser }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm install
          npm install mochawesome mochawesome-merge mochawesome-report-generator --save-dev

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress test on ${{ matrix.browser }}
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          config-file: cypress.c
